---
application:
  name: "rust-sdt"
  project: "rust-sdt"
  organization: "QoveryCommunity"
  publicly_accessible: true
databases:
  - type: "POSTGRESQL"
    name: "sdt"
    version: "11.5"
routers:
  - name: "main-rust-sdt"
    routes:
      - application_name: "rust-sdt"
        paths:
          - "/*"
